### PR TITLE
no quote for bigint

### PR DESCRIPTION
**Pull request by Marc-T**
no quote for bigint, in example with quote, where checksum = '10269470833408170953' return an empty result.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @Marc-T, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by Marc-T** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @Marc-T has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by akuzminsky** [comment]
@Marc-T : Hi Marc,

While the fix is useful the PR includes some other features. Some of them are irrelevant, like changes to bootstrap.sh.

Would you mind creating a separate PR for each change?

**Comment by Marc-T** [comment]
Hi Aleks,

I recreate my initial pull request.

**Pull request closed without merging**
